name: Build Python2 for Debian loong64

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Build Python2 for Debian loong64
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        variant:
          - kde
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/debian:trixie
          options: --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; 
            apt install devscripts equivs build-essential git -y
            git config --global --add safe.directory /work
            
            mk-build-deps -i -r
            make -f debian/rules control-file
            make -f debian/rules debian/patches/series
            DEB_BUILD_OPTIONS=nocheck,nobench dpkg-buildpackage -b -us -uc -tc

            mkdir artifacts
            mv ../*.deb artifacts/
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python2 for Debian loong64
          path: ${{ github.workspace }}/artifacts/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
